In [1]:
import numpy as np

In [2]:
list=[1,2,3]
list

[1, 2, 3]

In [3]:
np.array(list)

array([1, 2, 3])

In [5]:
matrix=[[1,2,3],[4,5,6],[7,8,9]]
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.linspace(0,10,3) ## return evenly spaced numbers over a specified interval


array([ 0.,  5., 10.])

In [18]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [20]:
np.eye(4) ## eys create an identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.random.rand(5)

array([0.0286181 , 0.18327602, 0.42172229, 0.88274853, 0.00559469])

In [24]:
np.random.rand(5,5)

array([[0.58004624, 0.93126354, 0.42276867, 0.58233195, 0.49272504],
       [0.18509219, 0.91254369, 0.62032975, 0.6704781 , 0.74460833],
       [0.18526254, 0.46870277, 0.32576796, 0.84843609, 0.30620044],
       [0.2146278 , 0.89514257, 0.50169025, 0.01915127, 0.40892455],
       [0.08304909, 0.63464276, 0.97473699, 0.89665361, 0.3391163 ]])

In [26]:
np.random.randn(5)

array([ 0.4704897 , -0.57867808, -1.12314581, -0.76090104,  0.06875014])

In [27]:
np.random.randn(5,5)

array([[ 0.01249052, -1.3633474 , -0.54932637,  1.42989169,  1.71643847],
       [-0.23082277, -1.12843695,  1.03654814, -2.57225283,  0.80660913],
       [-0.46758634, -0.67630033,  0.17710815, -1.55375684, -1.21942834],
       [ 0.43700064,  1.07435272,  0.05362783,  2.22147999,  0.9036065 ],
       [ 1.32832116,  0.65962474, -1.37574823,  0.44167708,  0.64339476]])

In [29]:
np.random.randint(1,5)

4

In [30]:
np.random.randint(1,300,10)

array([ 61,  16, 296, 155,  51, 284, 178, 100, 212,   1])

In [35]:
arr=np.arange(25)
ranarr=np.random.randint(0,50,9)


In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
ranarr

array([49, 31, 38, 24, 29,  9,  0, 12, 19])

In [34]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
ranarr.reshape(3,3)

array([[49, 31, 38],
       [24, 29,  9],
       [ 0, 12, 19]])

In [38]:
ranarr.max()

49

In [46]:
ranarr

array([ 0,  9, 12, 19, 24, 29, 31, 38, 49])

In [45]:
ranarr.argmax()

8

In [47]:
ranarr.argmin()

0

In [39]:
ranarr.min()

0

In [40]:
ranarr.mean()

23.444444444444443

In [42]:
ranarr.ndim

1

In [44]:
ranarr.std()

14.384490962384229

In [49]:
arr.shape

(25,)

In [50]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [51]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
arr.reshape(5,5).shape

(5, 5)