In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [5]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [6]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [7]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.random.randn(1)

array([1.31396219])

In [10]:
np.random.rand(25)

array([0.57244638, 0.98592951, 0.3528927 , 0.28400286, 0.04263197,
       0.74560588, 0.11582598, 0.17702939, 0.84825853, 0.99607229,
       0.21222841, 0.79262195, 0.93242811, 0.80289867, 0.58706347,
       0.52313157, 0.61183567, 0.01938652, 0.80644109, 0.15912419,
       0.30587086, 0.99896054, 0.15925532, 0.71583418, 0.92039966])

In [11]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [12]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [13]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [15]:
mat[3][4]

20

In [16]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [17]:
mat.max()

25

In [18]:
mat.min(
    
)

1

In [19]:
mat.sum()

325

In [20]:
mat.std()

7.211102550927978

In [21]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [22]:
import numpy as np

In [23]:
n = 390 
drift = 0.0002
vol = 0.01
returns = np.random.normal(drift, vol, n)
price = 100 * np.exp(np.cumsum(returns))

In [24]:
price

array([ 99.2789514 ,  99.15922706,  99.88003195,  99.70054643,
       100.41172499, 102.05431589, 102.33152455, 102.25752244,
       101.75215385, 101.22081651, 100.85547444,  99.66941669,
        99.22650656,  99.25088641,  99.76544194, 100.64029771,
       102.56197967, 104.77268201, 103.49955143, 102.0138922 ,
       101.31972474, 100.30211145, 100.32880877,  99.6048414 ,
        98.8425222 ,  99.06681448,  98.58219365,  98.32399611,
        99.44522186, 100.10620605,  99.11704999,  99.81054824,
        99.74861178,  98.20363256,  96.52805301,  98.98266654,
        99.59148743,  99.70741689,  98.97747849, 100.22190398,
       100.65067482,  99.35939105,  98.32576906,  98.94937989,
       100.75041174,  98.58674133,  99.39833147, 100.50420858,
       100.95719777, 102.4003997 , 105.59864891, 105.68105487,
       103.67931948, 105.28360285, 106.06222671, 107.00398156,
       105.05743845, 103.28681616, 103.94925984, 104.91929705,
       105.60506756, 105.65900507, 106.09472945, 107.37

 Expectation (E[X]) → profit expectancy

Variance (Var[X]) → risk

Correlation (Cov[X,Y]) → pair/hedge logic

Time differentials (dS, dt, dW) → price evolution

Optimization → maximizing Sharpe or execution efficiency

In [25]:
np.random.normal(0,2,10)

array([ 2.44916597, -0.20195625, -0.81672944, -1.72895502, -2.64922988,
        0.43526856, -0.84679549,  1.7418318 ,  1.66893706,  0.15573431])

In [ ]:
## Vectorizedd bid

bids=100+np.random.normal(0,0.05,n)
asks=bids+np.random.uniform(0.01,0.1,n)

In [27]:
## Slippage and order Impact Simulation
valume=np.random.randint(100,1000,n)
impact=np.random.uniform(0,0.002,n)
execution_price=price*(1+impact*(valume/valume.max()))
execution_price

array([ 99.33071562,  99.18490798,  99.91648272,  99.75133554,
       100.4804002 , 102.18458948, 102.3377944 , 102.38631593,
       101.83387326, 101.29209553, 100.85564735,  99.77879582,
        99.24964645,  99.30398782,  99.78932696, 100.6503713 ,
       102.59572019, 104.83693645, 103.65466191, 102.02336348,
       101.32803347, 100.30933593, 100.33123993,  99.69544793,
        98.88046542,  99.1956975 ,  98.63775265,  98.34247585,
        99.53908876, 100.22018711,  99.13049692,  99.86745848,
        99.81528877,  98.2865445 ,  96.52837822,  98.98864143,
        99.59437928,  99.77909777,  99.0019422 , 100.33430974,
       100.6823513 ,  99.38192483,  98.33705017,  98.99772604,
       100.78256138,  98.69726291,  99.5074646 , 100.52113908,
       101.03264971, 102.44402333, 105.64875476, 105.73149928,
       103.7109499 , 105.36123026, 106.11420242, 107.03728441,
       105.07923299, 103.3227053 , 103.99188043, 105.10269664,
       105.64541087, 105.73139792, 106.10337634, 107.39

In [29]:
## Moving Avg Crossover
## Detect buy/sell signals efficiently.
short_ma=np.convolve(price, np.ones(10)/10, mode='valid')
long_ma=np.convolve(price, np.ones(50)/50, mode='valid')
signals=np.where(short_ma[40:] > long_ma, 1, 0)
signals

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [31]:
## Z-Score Mean Reversion
## Identify extreme price deviations
window = 20
rolling_mean = np.convolve(price, np.ones(window)/window, 'valid')
rolling_std = np.sqrt(np.convolve((price[window-1:] - rolling_mean)**2, np.ones(window)/window, 'valid'))
z_score = (price[window*2-2:] - rolling_mean) / rolling_std
z_score

ValueError: operands could not be broadcast together with shapes (352,) (371,) 