In [2]:
import numpy as np


In [3]:
arr=np.arange(5,20)
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [4]:
arr[4]

9

In [5]:
arr[1:5]

array([6, 7, 8, 9])

In [6]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19])

In [11]:
arr=np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [12]:
s_arr=arr[0:7]
s_arr

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
copy_arr=arr.copy()
copy_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### 2D array

In [15]:
arr2d=arr.reshape(3,4)
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
arr2d[1]

array([5, 6, 7, 8])

In [17]:
arr2d[1][2]

7

In [21]:
arr2d[1,2]

7

In [23]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
arr2d[:2,1:]

array([[2, 3, 4],
       [6, 7, 8]])

In [27]:
arr2d[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Fancy Indexing

In [28]:
arr_2d=np.zeros((10,10))
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
arr_lenght=arr_2d.shape[1]
arr_lenght

10

In [32]:
for i in range(arr_lenght):
    arr_2d[i]=i
    
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [33]:
arr_2d[[2,3,4,5]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [34]:
## allows in any order
arr_2d[[2,4,6,1]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### More Indexing Help

In [40]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [42]:
arr>14

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [43]:
bool_arr=arr>14
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [44]:
arr[bool_arr]

array([15, 16, 17, 18, 19, 20])

In [45]:
arr[arr>12]

array([13, 14, 15, 16, 17, 18, 19, 20])