In [1]:
import numpy as np

In [11]:
arr=np.arange(0,9)
arr.shape

(9,)

In [12]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [13]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64])

In [14]:
arr/arr

/tmp/ipykernel_8597/1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [15]:
arr//arr

/tmp/ipykernel_8597/3990451985.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  arr//arr


array([0, 1, 1, 1, 1, 1, 1, 1, 1])

In [16]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
1/arr

/tmp/ipykernel_8597/255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     ])

In [18]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512])

### Universal Array Functions

In [19]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712])

In [20]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03])

In [21]:
np.max(arr)

8

In [22]:
np.msort(arr)

/tmp/ipykernel_8597/4024110395.py:1: DeprecationWarning: msort is deprecated, use np.sort(a, axis=0) instead
  np.msort(arr)


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825])

In [25]:
np.log(arr)

/tmp/ipykernel_8597/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154])

In [26]:
np.log10(arr)

/tmp/ipykernel_8597/2153533263.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(arr)


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999])